version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
  settings:
    goimports:
      local-prefixes:
        - github.com/lex00/aws-sam-translator-go
